// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWvGleuHLrcYwkpBFdaeWL9cKClERbko',
    appId: '1:648135491811:web:84d1afdedf6b96f975c5d6',
    messagingSenderId: '648135491811',
    projectId: 'e-book-app-4067f',
    authDomain: 'e-book-app-4067f.firebaseapp.com',
    storageBucket: 'e-book-app-4067f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLAEOXjHPd4pM_rKJfCkcjmpoOM0FZm4',
    appId: '1:648135491811:android:ba153533a082bcbb75c5d6',
    messagingSenderId: '648135491811',
    projectId: 'e-book-app-4067f',
    storageBucket: 'e-book-app-4067f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7vCqDNML6Yk-ZcqpvX4iyYdp1eBZIPk',
    appId: '1:648135491811:ios:4b81113510baf50a75c5d6',
    messagingSenderId: '648135491811',
    projectId: 'e-book-app-4067f',
    storageBucket: 'e-book-app-4067f.appspot.com',
    iosClientId: '648135491811-bqnbhkg8q219adijf4c9jain7ij7h6ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7vCqDNML6Yk-ZcqpvX4iyYdp1eBZIPk',
    appId: '1:648135491811:ios:62c2f3117beabfdc75c5d6',
    messagingSenderId: '648135491811',
    projectId: 'e-book-app-4067f',
    storageBucket: 'e-book-app-4067f.appspot.com',
    iosClientId: '648135491811-e6talmh771isp3i1rnj0s1579g0knqlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebook.RunnerTests',
  );
}
